bundles:
	bash retrieve-ds-bundles.sh

bundles-dash:
	bash retrieve-ds-bundles-dash.sh

bundles-CM:
	bash retrieve-ds-bundles-cert-manger.sh

update-config:
	pip install -r requirements.txt
	python update-config.py
