apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: alertmanager-to-github-secrets
  namespace: alertmanager-to-github
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: alertmanager-to-github-secret-gen
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: alertmanager-to-github
                  namespace: alertmanager-to-github
                type: Opaque
                stringData:
                  ATG_GITHUB_TOKEN: '{{fromSecret "open-cluster-management" "kcp-sgs-pipelines-secrets-config" "githubToken" | base64dec }}'
        remediationAction: inform
        severity: low
  remediationAction: enforce

---

apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-alertmanager-to-github-secrets
  namespace: alertmanager-to-github
placementRef:
  name: placement-alertmanager-to-github-secrets
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: alertmanager-to-github-secrets
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-alertmanager-to-github-secrets
  namespace: alertmanager-to-github
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: "local-cluster", operator: In, values: ["true"]}
