apiVersion: monitoring.rhobs/v1
kind: ServiceMonitor
metadata:
  name: clusterlifecycle-state-metrics-v2-rhobs
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 60s
    port: https
    scheme: https
    scrapeTimeout: 10s
    tlsConfig:
      insecureSkipVerify: true
  jobLabel: clc-app
  namespaceSelector:
    matchNames:
    - multicluster-engine
  selector:
    matchLabels:
      clc-app: clusterlifecycle-state-metrics-v2
