apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: multiclusterengine-catalog
  namespace: openshift-marketplace
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  displayName: MultiCluster Engine
  image: quay.io/acm-d/mce-custom-registry:v2.0.1-RC1
  publisher: Red Hat
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 10m
  secrets:
  - acm-pull-secret
