# This is a basic workflow to help you get started with Actions

name: Update OSD Addon Config

# Controls when the action will run. 
on:
  # Runs every day
  schedule:
    - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        # with:
        #   token: ${{ secrets.REPO_TOKEN }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      # Runs a set of commands using the runners shell
      - name: Update OSD Addon Config
        env:
          QUAY_BEARER_TOKEN: ${{ secrets.QUAY_BEARER_TOKEN }}
        run: |
          cd addon-bundling/
          make update-config
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          signoff: true
          branch: "update-osd-addon-config"
          delete-branch: true
          title: "OSD Addon Config Update"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          labels: do-not-merge/hold
          assignees: zkayyali812
          commit_options: '--signoff'
          file_pattern: addon-bundling/config.yaml 
